spring.config.import=optional:file:.env[.properties]

spring.application.name=EventSync-API
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=${PGSSLMODE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=eventsync_app
spring.jpa.properties.hibernate.format_sql=true

security.jwt.token.secret-key=${JWT_SECRET}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}


